### ISSUE TITLE
Contract improvements

### ISSUE THREAD

**Issue by svetoslavpetkov** [valentinemilov/Rental-car-app#6]
CreateContractDTO pickupDate and estimatedReturnDate to be Date

Create contract Validations 
- carID uuid
- check car exists
- check car isAvailable
- pickUpDate - should be removed , pickUpDate is calculated on back-end  = now
- estimatedReturnDate > pickUpDate

Create contract improvements
Transaction on save car and save contract.
instead of contractEnity.car = Promise.resolve(carToBeHired); try setting contractEnity.car wiehout promise

Close contract Validations:
- contractId is valid uuid
- dateToReturn not in request, but calc on server = now()
- contract is existing
- contract is not closed
- Return car should be in transaction

**Comment by valentinemilov** [comment]
https://github.com/valentinemilov/Rental-car-app/issues/6
